apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: my-app
  name: my-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-app
    spec:
      containers:
      - image: utheman/example_aui:0.7.0
        name: my-app
        env:
          - name: MESSAGE_VALUE_KEY
            valueFrom:
              configMapKeyRef:
                name: message-config
                key: MESSAGE_VALUE
          - name: MY_APP_DB_HOST
            value: aui-mongodb
          - name: MY_APP_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongodb-pass
                key: password
        ports:
          - containerPort: 8080