apiVersion: v1
kind: Service
metadata:
  name: aui-mongodb
  labels:
    app: my-app
spec:
  ports:
    - port: 3306
  selector:
    app: my-app
    tier: mongodb
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pv-claim
  labels:
    tier: mongodb
    app: my-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: aui-mongodb
  labels:
    tier: mongodb
    app: my-app
spec:
  serviceName: "aui-mongodb"
  replicas: 1
  selector:
    matchLabels:
      app: my-app
      tier: mongodb
  template:
    metadata:
      labels:
        app: my-app
        tier: mongodb
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongodb
          image: mongo:latest
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: myclaim
              mountPath: /data/db
          resources:
            requests:
              cpu: "250m"
  volumeClaimTemplates:
  - metadata:
      name: myclaim
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
